apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: Z2hwX1h0bmUxSjhhUGRhWmZzUzZkWnpMQThJTVF2dWZ1TDBEZXMySQ==
  BACKEND_SECRET: VGpEeEFxdE5RNW45UDh6SXZaSU1XSjVTV3FuS1Z1YVE=
  CUSTOM_SESSION_SECRET: VGpEeEFxdE5RNW45UDh6SXZaSU1XSjVTV3FuS1Z1YVE=
  AUTH_GOOGLE_CLIENT_ID: Mzg5NTg0OTIxMTI4LTQybDJjMWZoM2N1c2xkNjRtczVycW8wNWQ3cWNtajRmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  AUTH_GOOGLE_CLIENT_SECRET: R09DU1BYLTgyU1E0X2tqZ0ZPaHc0c0JZYmJ6bWtVOUtSR2Q=
