apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  BACKEND_SECRET: VGpEeEFxdE5RNW45UDh6SXZaSU1XSjVTV3FuS1Z1YVE=
  CUSTOM_SESSION_SECRET: VGpEeEFxdE5RNW45UDh6SXZaSU1XSjVTV3FuS1Z1YVE=
